development:
  adapter: postgresql
  encoding: unicode
  database: wikilicious_development
  pool: 5
  username: wikilicious
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: wikilicious_production
  pool: 5
  username: wikilicious
  password:
